# -*- coding: utf-8 -*-
"""Real time context (AI & ML task 4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfSAstXqoEP45krOgo9sB2fHRiy-nbAg
"""

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.pipeline import Pipeline

from sklearn.metrics import accuracy_score

df = pd.read_csv("customer_feedback.csv")

print(df.head())

print(df.shape)

print(df.info())

print(df["Category"].value_counts())

X = df["Feedback"]

y = df["Category"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

model = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("classifier", MultinomialNB())
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

feedback = ["The payment failed and I was charged twice"]

prediction = model.predict(feedback)

print(prediction[0])

feedback = input("Enter customer feedback: ")

prediction = model.predict([feedback])[0]

department = {
    "Billing": "Finance Team",
    "Delivery": "Logistics Team",
    "Product": "Quality Assurance Team",
    "Technical Support": "IT Support Team",
    "General Inquiry": "Customer Care Team"
}

print("\nPredicted Category :", prediction)
print("Route To :", department[prediction])

import matplotlib.pyplot as plt

category_counts = df["Category"].value_counts()

plt.figure(figsize=(8,5))
category_counts.plot(kind="bar")

plt.xlabel("Feedback Category")
plt.ylabel("Number of Feedbacks")
plt.title("Customer Feedback Category Distribution")

plt.xticks(rotation=45)
plt.show()

pip install wordcloud

from wordcloud import WordCloud
import matplotlib.pyplot as plt


text = " ".join(df["Feedback"])


wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white"
).generate(text)


plt.figure(figsize=(10,5))

plt.imshow(wordcloud)

plt.axis("off")

plt.title("Most Common Words in Customer Feedback")

plt.show()